"""
Django settings for situations project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os


# this is the production/development and live switch
DEV_MODES = [
    (0, 'LOCAL'),
    (1, 'PROD'),
    (2, 'LIVE'),
]
DEV_MODE = 0

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# site domain
if DEV_MODE is 0:
    DOMAIN = 'localhost'
if DEV_MODE is 1:
    DOMAIN = 'http://dev.pixelkante.com/'
if DEV_MODE is 2:
    DOMAIN = 'http://live.pixelkante.com/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '19dfmvd1b#a3hljytm_&1i_4ifg4#fx3x2qq@xfqun731!(l$8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'dev.pixelkante.com',               # dev
    'situations.dergreif-online.de',    # live
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'gallery.apps.GalleryConfig',   # added gallery app
    'django_ajax',                  # added django_ajax
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'situations.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',


            ],
        },
    },
]

WSGI_APPLICATION = 'situations.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

if DEV_MODE is 0:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
if DEV_MODE is 1:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'situations_mysql',
            'USER': 'pixelkante',
            'PASSWORD': 'djangohelden',
            'HOST': 'web456.webfaction.com',
            'PORT': '3306',
        }
    }
if DEV_MODE is 2:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'situations_live_db',
            'USER': 'dergreif',
            'PASSWORD': 'ScbjG7R5tZYdGUpZ',
            'HOST': 'web456.webfaction.com',
            'PORT': '3306',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
if DEV_MODE is 0:
    STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR) + '/static/', 'static')
if DEV_MODE is 1:
    STATIC_ROOT = '/home/soley/webapps/situations_static/'
if DEV_MODE is 2:
    STATIC_ROOT = '/home/soley/webapps/situations_live_static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'templates/static'),     # for future projects: this is not where the static folder should be
    os.path.join(BASE_DIR, 'gallery/static/gallery/'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR) + '/situations/', 'media')
# These are messed up settings, but for now they work - dont do this this in future projects

# Mail
"""
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'greif.situation@gmail.com'
EMAIL_HOST_PASSWORD = 'DasIstSicher123'
DEFAULT_FROM_EMAIL = 'greif.situation@gmail.com'
DEFAULT_TO_EMAIL = 'buddy.oley@gmail.com'
"""
EMAIL_USE_TLS = True
EMAIL_HOST = 'w00c93ee.kasserver.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'm03aaa83'
EMAIL_HOST_PASSWORD = 'GeMU7795yeVBxBHB'
DEFAULT_FROM_EMAIL = 'situations@dergreif-online.de'
DEFAULT_TO_EMAIL = 'situations@dergreif-online.de'

# GeoIP files
GEOIP_PATH = BASE_DIR + '/geoip'

# Google API
GOOGLE_API_KEY = 'AIzaSyBs4ZYShxicQyYy_lZ5cOJlcFUqHHw1V9M'

# Colors
COLORS = [
    (0, '#9036fe'),     # id color (purple)
    (1, '#ffffff'),     # background
    (2, '#f8f9fa'),     # light grey    - e.g. nav
    (3, '#dddddd'),     # medium grey   - e.g. map
]

# Map
MAP_MODE = 0            # 0 = all, 1 = only markers, 2 = limited markers
MAP_LIMIT = 100         # num of markers shown on map for mode != 0
