# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('title', models.CharField(default='Some Title', max_length=50)),
                ('author', models.CharField(default='Some Author', max_length=50)),
                ('date_photo_taken', models.DateTimeField(default=datetime.datetime(2016, 9, 5, 9, 57, 48, 274826, tzinfo=utc), verbose_name='year photo taken')),
                ('location', models.CharField(default='Some City', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=datetime.datetime(2016, 9, 5, 9, 57, 48, 274826, tzinfo=utc))),
                ('description', models.CharField(default='Some description', max_length=200)),
                ('reason', models.CharField(default='Some Reason', max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_id', models.UUIDField(default=uuid.uuid4)),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
                ('name', models.CharField(default='294800', max_length=50, verbose_name='name')),
                ('city', models.CharField(blank=True, default='some city', max_length=50, null=True)),
                ('country', models.CharField(blank=True, default='some country', max_length=50, null=True)),
                ('region', models.CharField(blank=True, default='some region', max_length=50, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_time', models.DurationField(blank=True, default=datetime.timedelta(0, 60), null=True, verbose_name='time spent to publish')),
                ('session_start', models.DateTimeField(blank=True, null=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('year_of_birth', models.IntegerField(blank=True, choices=[(0, 2006), (1, 2005), (2, 2004), (3, 2003), (4, 2002), (5, 2001), (6, 2000), (7, 1999), (8, 1998), (9, 1997), (10, 1996), (11, 1995), (12, 1994), (13, 1993), (14, 1992), (15, 1991), (16, 1990), (17, 1989), (18, 1988), (19, 1987), (20, 1986), (21, 1985), (22, 1984), (23, 1983), (24, 1982), (25, 1981), (26, 1980), (27, 1979), (28, 1978), (29, 1977), (30, 1976), (31, 1975), (32, 1974), (33, 1973), (34, 1972), (35, 1971), (36, 1970), (37, 1969), (38, 1968), (39, 1967), (40, 1966), (41, 1965), (42, 1964), (43, 1963), (44, 1962), (45, 1961), (46, 1960), (47, 1959), (48, 1958), (49, 1957), (50, 1956), (51, 1955), (52, 1954), (53, 1953), (54, 1952), (55, 1951), (56, 1950), (57, 1949), (58, 1948), (59, 1947), (60, 1946), (61, 1945), (62, 1944), (63, 1943), (64, 1942), (65, 1941), (66, 1940), (67, 1939), (68, 1938), (69, 1937), (70, 1936), (71, 1935), (72, 1934), (73, 1933), (74, 1932), (75, 1931), (76, 1930), (77, 1929), (78, 1928), (79, 1927), (80, 1926), (81, 1925), (82, 1924), (83, 1923), (84, 1922), (85, 1921), (86, 1920), (87, 1919), (88, 1918), (89, 1917), (90, 1916), (91, 1915), (92, 1914), (93, 1913), (94, 1912), (95, 1911), (96, 1910), (97, 1909), (98, 1908), (99, 1907), (100, 1906), (101, 1905), (102, 1904), (103, 1903), (104, 1902), (105, 1901)], default=0, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('occupation', models.IntegerField(choices=[(0, 'Management'), (1, 'Office/Administrative Support'), (2, 'Business and Financial Operations '), (3, 'Architecture/Engineering'), (4, 'Art and Design'), (5, 'Entertainer/Performer'), (6, 'Media and Communications'), (7, 'Computer/Mathematical'), (8, 'Farming/Fishing/Forestry Worker'), (9, 'Building and Grounds Cleaning and Maintenance'), (10, 'Life Science'), (11, 'Physical Science'), (12, 'Military and Protective Service'), (13, 'Healthcare Practitioner or Technician'), (14, 'Healthcare Support'), (15, 'Community and Social Service'), (16, 'Social Science'), (17, 'Legal Occupations'), (18, 'Education/Training/Library'), (19, 'Transportation'), (20, 'Personal Care and Service'), (21, 'Construction/Installation/Repair'), (22, 'Food Preparation/Serving'), (23, 'Sales'), (24, 'Production/Manufacturing')], default=0)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Publisher')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Publisher'),
        ),
    ]
