# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('year', models.DateTimeField(verbose_name='year published')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=500)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('alias', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
                ('zip_code', models.IntegerField(verbose_name='zip code')),
                ('is_active', models.BooleanField(default=True)),
                ('active_time', models.DurationField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('occupation', models.IntegerField(choices=[(0, 'Management'), (1, 'Office/Administrative Support'), (2, 'Business and Financial Operations '), (3, 'Architecture/Engineering'), (4, 'Art and Design'), (5, 'Entertainer/Performer'), (6, 'Media and Communications'), (7, 'Computer/Mathematical '), (8, 'Farming/Fishing/Forestry Worker'), (9, 'Building and Grounds Cleaning and Maintenance'), (10, 'Life Science'), (11, 'Physical Science'), (12, 'Military and Protective Service'), (13, 'Healthcare Practitioner or Technician'), (14, 'Healthcare Support'), (15, 'Community and Social Service'), (16, 'Social Science'), (17, 'Legal Occupations'), (18, 'Education/Training/Library'), (19, 'Transportation'), (20, 'Personal Care and Service'), (21, 'Construction/Installation/Repair'), (22, 'Food Preparation/Serving'), (23, 'Sales'), (24, 'Production/Manufacturing')], default=0)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Publisher')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Publisher'),
        ),
    ]
