# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('title', models.CharField(default='Some Title', max_length=50)),
                ('author', models.CharField(default='Some Author', max_length=50)),
                ('date_photo_taken', models.DateTimeField(default=datetime.datetime(2016, 8, 24, 17, 27, 13, 918913), verbose_name='year photo taken')),
                ('location', models.CharField(default='Some City', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=datetime.datetime(2016, 8, 24, 17, 27, 13, 918913))),
                ('description', models.CharField(default='Some description', max_length=200)),
                ('reason', models.CharField(default='Some Reason', max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_id', models.UUIDField(default=uuid.uuid4)),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_time', models.DurationField(blank=True, null=True, verbose_name='time spent to publish')),
                ('year_of_birth', models.IntegerField(blank=True, choices=[(1990, 'so ein quatsch'), (1991, 'so ein quatsch'), (1992, 'so ein quatsch'), (1993, 'so ein quatsch'), (1994, 'so ein quatsch'), (1995, 'so ein quatsch'), (1996, 'so ein quatsch'), (1997, 'so ein quatsch'), (1998, 'so ein quatsch'), (1999, 'so ein quatsch')], null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('occupation', models.IntegerField(choices=[(0, 'Management'), (1, 'Office/Administrative Support'), (2, 'Business and Financial Operations '), (3, 'Architecture/Engineering'), (4, 'Art and Design'), (5, 'Entertainer/Performer'), (6, 'Media and Communications'), (7, 'Computer/Mathematical'), (8, 'Farming/Fishing/Forestry Worker'), (9, 'Building and Grounds Cleaning and Maintenance'), (10, 'Life Science'), (11, 'Physical Science'), (12, 'Military and Protective Service'), (13, 'Healthcare Practitioner or Technician'), (14, 'Healthcare Support'), (15, 'Community and Social Service'), (16, 'Social Science'), (17, 'Legal Occupations'), (18, 'Education/Training/Library'), (19, 'Transportation'), (20, 'Personal Care and Service'), (21, 'Construction/Installation/Repair'), (22, 'Food Preparation/Serving'), (23, 'Sales'), (24, 'Production/Manufacturing')], default=0)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Publisher')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Publisher'),
        ),
    ]
