# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 20, 1, 18, 460238)),
        ),
    ]
