# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date_photo_taken',
        ),
        migrations.AddField(
            model_name='image',
            name='year_photo_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='788581', max_length=50, verbose_name='name'),
        ),
    ]
