# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='last_session_start',
            new_name='session_end',
        ),
        migrations.AddField(
            model_name='publisher',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_photo_taken',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 2, 14, 55, 56, 802499), verbose_name='year photo taken'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 2, 14, 55, 56, 803499)),
        ),
    ]
