# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_photo_taken',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 30, 16, 53, 7, 671985), verbose_name='year photo taken'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 30, 16, 53, 7, 672486)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='year_of_birth',
            field=models.IntegerField(blank=True, choices=[(0, 2006), (1, 2005), (2, 2004), (3, 2003), (4, 2002), (5, 2001), (6, 2000), (7, 1999), (8, 1998), (9, 1997), (10, 1996), (11, 1995), (12, 1994), (13, 1993), (14, 1992), (15, 1991), (16, 1990), (17, 1989), (18, 1988), (19, 1987), (20, 1986), (21, 1985), (22, 1984), (23, 1983), (24, 1982), (25, 1981), (26, 1980), (27, 1979), (28, 1978), (29, 1977), (30, 1976), (31, 1975), (32, 1974), (33, 1973), (34, 1972), (35, 1971), (36, 1970), (37, 1969), (38, 1968), (39, 1967), (40, 1966), (41, 1965), (42, 1964), (43, 1963), (44, 1962), (45, 1961), (46, 1960), (47, 1959), (48, 1958), (49, 1957), (50, 1956), (51, 1955), (52, 1954), (53, 1953), (54, 1952), (55, 1951), (56, 1950), (57, 1949), (58, 1948), (59, 1947), (60, 1946), (61, 1945), (62, 1944), (63, 1943), (64, 1942), (65, 1941), (66, 1940), (67, 1939), (68, 1938), (69, 1937), (70, 1936), (71, 1935), (72, 1934), (73, 1933), (74, 1932), (75, 1931), (76, 1930), (77, 1929), (78, 1928), (79, 1927), (80, 1926), (81, 1925), (82, 1924), (83, 1923), (84, 1922), (85, 1921), (86, 1920), (87, 1919), (88, 1918), (89, 1917), (90, 1916), (91, 1915), (92, 1914), (93, 1913), (94, 1912), (95, 1911), (96, 1910), (97, 1909), (98, 1908), (99, 1907), (100, 1906), (101, 1905), (102, 1904), (103, 1903), (104, 1902), (105, 1901)], null=True),
        ),
    ]
