# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160823_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_photo_taken',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 20, 5, 35, 576594), verbose_name='year photo taken'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 20, 5, 35, 577595)),
        ),
    ]
