# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160902_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_photo_taken',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 9, 28, 9, 297461, tzinfo=utc), verbose_name='year photo taken'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 9, 28, 9, 298608, tzinfo=utc)),
        ),
    ]
