# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160903_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='000000-0', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_photo_taken',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 11, 35, 18, 675721, tzinfo=utc), verbose_name='year photo taken'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 11, 35, 18, 676966, tzinfo=utc)),
        ),
    ]
