# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160903_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_photo_taken',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 11, 46, 39, 380480, tzinfo=utc), verbose_name='year photo taken'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 11, 46, 39, 381545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='241316-<built-in function id>', max_length=50, verbose_name='name'),
        ),
    ]
