# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160819_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='active_time',
            field=models.DurationField(blank=True, null=True, verbose_name='time spent to publish'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Publisher'),
        ),
    ]
