# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20160822_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='some name, only for admin purpose while testing'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='alias',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
