# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20160823_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='e-mail'),
        ),
    ]
