# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20160903_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_photo_taken',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 13, 48, 32, 661727, tzinfo=utc), verbose_name='year photo taken'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 13, 48, 32, 662970, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='313090', max_length=50, verbose_name='name'),
        ),
    ]
