# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_publisher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='some name, only for identification purpose while testing'),
        ),
    ]
